BEGIN TRANSACTION;

    DROP TABLE IF EXISTS Genero;
    
COMMIT TRANSACTION;

BEGIN TRANSACTION;

    CREATE TABLE Genero(
        IdGenero CHAR(32) NOT NULL,
        Nome VARCHAR(255) NOT NULL,
        PRIMARY KEY(IdGenero)
    );

COMMIT TRANSACTION;