BEGIN TRANSACTION;

    DROP TABLE IF EXISTS Turno;
    
COMMIT TRANSACTION;

BEGIN TRANSACTION;

    CREATE TABLE Turno(
        IdTurno VARCHAR(36) NOT NULL,
        Nome VARCHAR(255) NOT NULL,
        PRIMARY KEY(IdTurno)
    );
    
COMMIT TRANSACTION;